# Generated by Django 5.2.16 on 2026-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=200),
            preserve_default=False,
        ),
    ]
